### PR TITLE
Separated the files - CSS and JS files

### PR DESCRIPTION
**Pull request by pranjal-arora**

### CODE REVIEW

**Comment by aradhya-gupta** [comment]
Did you check if the website was working properly on your local machine after making these changes?

**Comment by pranjal-arora** [comment]
> Did you check if the website was working properly on your local machine after making these changes?

yes @aradhya-gupta i did check it, it was working fine.

**Comment by pranjal-arora** [comment]
@aradhya-gupta, the checks might be failing due to addition of a new file (script.js). i request you to redeploy the site.

**Comment by aradhya-gupta** [comment]
> @aradhya-gupta, the checks might be failing due to addition of a new file (script.js). i request you to redeploy the site.

Just add all the js code to index.js file

**Comment by pranjal-arora** [comment]
> > @aradhya-gupta, the checks might be failing due to addition of a new file (script.js). i request you to redeploy the site.
> 
> Just add all the js code to index.js file

@aradhya-gupta done! shifted the js code to index.js

**Comment by pranjal-arora** [comment]
@aradhya-gupta sir i request you to at please give my PR a hacktoberfest-accepted label

**Pull request merged**
